import json
from pathlib import Path

json_path = Path("data/spec-redirects.json")
content_dir = Path("content")
# We move the generation to a separate top-level folder
redirect_dir = Path("content/redirects")

def generate_stubs():
    if not json_path.exists():
        print("Error: data/spec-redirects.json not found.")
        return

    with open(json_path, 'r', encoding='utf-8') as f:
        redirects = json.load(f)

    for item in redirects:

        # 'old' is something like '/standards/biopax/'
        target_url = item['old'] 
        
        # Create a unique filename for the redirect folder
        # e.g., 'standards-biopax'
        file_slug = target_url.strip('/').replace('/', '-')
        
        target_dir = redirect_dir / file_slug
        target_dir.mkdir(parents=True, exist_ok=True)
        
        file_path = target_dir / "index.md"
        
        content = (
            "---\n"
            "# WARNING: THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.\n"
            "# Target: " + item['new'] + "\n"
            f'title: "Redirect {file_slug}"\n'
            f'type: "external-redirect"\n'
            f'url: "{target_url}"\n'  # THIS IS THE KEY: It forces the URL
            f'redirect_target: "{item["new"]}"\n'
            "sitemap:\n"
            "  priority: 0\n"
            "---\n"
        )
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
    print(f"Generated {len(redirects)} redirects in content/redirects/")

if __name__ == "__main__":
    generate_stubs()
